experiment: groningen_1995_2025
source_data_root: data/resources
calibration_root: data/generated_calibrations
artifact_dir: data/generated_assessment
perspectives:
  - prospective
  - retrospective
models:
  - ETS_rmax_etasKac
  - EVTS_rmax_etasKac
  - ETS_bs4_etasKac
  - EVTS_bs4_etasKac
model_names:
  ETS_rmax_etasKac: ETS-ETF
  EVTS_rmax_etasKac: EVTS-ETF
  ETS_bs4_etasKac: ETS-BS4-ETF
  EVTS_bs4_etasKac: EVTS-BS4-ETF
pa_sample_size: 10000
seed: 1234
workers: 1
timeframe_testing:
  - 2020-10-01
  - 2025-10-01
timeframe_forecast:
  - 1995-01-01
  - 2025-10-01